name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hackassembler-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: HackAssembler

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install C++ compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile Unit Tests
        run: |
          g++ -std=c++20 -Iinclude src/parser.cpp tests/testParser.cpp -o tests/runParserTests
          g++ -std=c++20 -Iinclude src/parser.cpp src/code.cpp tests/testCode.cpp -o tests/runCodeTests

      - name: Run Unit Tests
        run: |
          tests/runParserTests
          tests/runCodeTests

      
