name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code repository
        uses: actions/checkout@main

      - name: Install C++ compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile HackAssembler Unit Tests
        run: |
          g++ -std=c++20 -Iinclude HackAssembler/src/parser.cpp HackAssembler/tests/testParser.cpp -o HackAssembler/tests/runParserTests
          g++ -std=c++20 -Iinclude HackAssembler/src/parser.cpp HackAssembler/src/code.cpp HackAssembler/tests/testCode.cpp -o HackAssembler/tests/runCodeTests

      # Step 4: Execute the test binary
      - name: Run Unit Tests
        run: |
          HackAssembler/tests/runParserTests
          HackAssembler/tests/runCodeTests

      
